batch_size: 256
num_devices: 1

wandb: true
project_name: noise_label
entity: dmlab_yj

dataset: tinyimagenet
data_folder: /home/yujin/robust-ood-noisy-labels-2/openood/data #경로수정정
resized_crop_scale: 0.2
label_file: /home/yujin/robust-ood-noisy-labels-2/openood/data/benchmark_imglist/tinyimagenet/train_tin_sym_0.2.txt
encoder_name: resnet18_64x64
epochs: 300
feat_dim: 256
img_size: 64
learning_rate: 0.03
learning_eta_min: 0.01
syncbn: false
reassign: 1
save_freq: 50
temp: 0.25
use_gaussian_blur: false
warmup_epochs: 20
weight_decay: 0.001
dist: false
num_workers: 32

model_name: tcl
sep_gmm: true
mixup_alpha: 1.0
seed: 2
save_checkpoints: true
